### ISSUE TITLE
how to achieve .jbignore

### ISSUE THREAD

**Issue by mrgleeco** [jsonnet-bundler/jsonnet-bundler#22]
hello - as a fan & user, wondering if this functionality exists:
in some cases, having certain files omitted from the bundle is desirable.  An ignore file -a la `.gitignore` seems useful & general purpose enough.  If this is doable today, i'm listening!
If it should be a feature request, let us know!

**Comment by metalmatze** [comment]
When `jb install` or `jb update` is run it simply clones the repository and then does a checkout of that revision (specified in `jsonnetfile.json` or `jsonnetfile.lock.json`). Those contents are then copied to your projects `vendor/`.

If you do commit these files to your repository (I don't have seen a project yet which does this for jsonnet-bundler dependencies) I currently don't see a use case where the normal `.gitignore` is not enough. Prefixing the files with `vendor/` in that `.gitignore` should do the trick.

Am I missing something? Just let us know.

**Comment by sh0rez** [comment]
If you don't want something to be installed, add it to `.gitignore`, so that it does not end up in the remote repository.

`jb` is not able to not clone something, the only possible thing is to download it and remove afterwards, which seems pointless both from a performance and security perspective.

Reopen if we are missing something. Thanks :D
