### ISSUE TITLE
ssh: Could not resolve hostname

### ISSUE THREAD

**Issue by hangxie** [jsonnet-bundler/jsonnet-bundler#67]
Broken in master:
```
$ rm -rf *
$ GO111MODULE="on" go get github.com/jsonnet-bundler/jsonnet-bundler/cmd/jb@master
go: finding github.com master
go: finding github.com/jsonnet-bundler/jsonnet-bundler master
go: finding github.com/jsonnet-bundler/jsonnet-bundler/cmd master
go: finding github.com/jsonnet-bundler/jsonnet-bundler/cmd/jb master
go: finding github.com/jsonnet-bundler master
$ jb --version
v0.2.1-0.20200124070234-7b8a7836a495
$ jb init
$ jb install git+ssh://git@github.com:hangxie/kustomize-libsonnet.git@test-branch
Initialized empty Git repository in /home/xiehang/tmp/jb/vendor/.tmp/jsonnetpkg-github.com-hangxie-kustomize-libsonnet-test-branch532767166/.git/
ssh: Could not resolve hostname github.com:hangxie: Name or service not known
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
ssh: Could not resolve hostname github.com:hangxie: Name or service not known
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
jb: error: failed to install packages: downloading: exit status 128
```

Things worked with 0.2.0:
```
$ rm -rf *
$ GO111MODULE="on" go get github.com/jsonnet-bundler/jsonnet-bundler/cmd/jb
$ jb --version
v0.2.0
$ jb init
$ jb install git+ssh://git@github.com:hangxie/kustomize-libsonnet.git@test-branch
Initialized empty Git repository in /home/xiehang/tmp/jb/vendor/.tmp/jsonnetpkg-kustomize-libsonnet-test-branch247024765/.git/
remote: Enumerating objects: 11, done.
remote: Counting objects: 100% (11/11), done.
remote: Compressing objects: 100% (11/11), done.
remote: Total 11 (delta 0), reused 7 (delta 0), pack-reused 0
Unpacking objects: 100% (11/11), done.
From github.com:hangxie/kustomize-libsonnet
 * branch            test-branch -> FETCH_HEAD
 * [new tag]         test-tag    -> test-tag
 * [new branch]      test-branch -> origin/test-branch
Branch 'test-branch' set up to track remote branch 'test-branch' from 'origin'.
Switched to a new branch 'test-branch'
```

**Comment by hangxie** [comment]
This syntax works for both v0.2.0 and master:
```
$ jb install git+ssh://git@github.com/hangxie/kustomize-libsonnet.git@test-branch
GET https://github.com/hangxie/kustomize-libsonnet/archive/bcc67b0df5f9576614ff979d83460c2def2c691e.tar.gz 200
```

I'm going to read doc again and close this if the format is mentioned

**Comment by hangxie** [comment]
I feel like https://github.com/jsonnet-bundler/jsonnet-bundler/blob/master/spec/deps/git.go#L103, the `:` between host and user should be `/`, then it can take `git+ssh://git@github.com:org/repo.git` pattern without failing back to HTTPS.

git CLI takes both `git+ssh://git@github.com:org/repo.git` and `git+ssh://git@github.com/org/repo.git` to me, I'm running git 2.17.1 if it matters.

**Comment by hangxie** [comment]
This works for me:
```
$ git diff
diff --git a/spec/deps/git.go b/spec/deps/git.go
index e547850..413d985 100644
--- a/spec/deps/git.go
+++ b/spec/deps/git.go
@@ -87,7 +87,7 @@ func (gs *Git) LegacyName() string {
 }

 var gitProtoFmts = map[string]string{
-       GitSchemeSSH:   GitSchemeSSH + "%s:%s/%s.git",
+       GitSchemeSSH:   GitSchemeSSH + "%s/%s/%s.git",
        GitSchemeHTTPS: GitSchemeHTTPS + "%s/%s/%s",
 }
```

**Comment by hangxie** [comment]
#68 shows the fix worked for me, feel free to discard if and file a new one with better fix, I'm not sure if we want to use `:` or `/` as delimiter between host and user, or support both.

**Comment by sh0rez** [comment]
This issue is related to the supported git protocols, which I apparently mixed up a little bit in my change.

According to `man git-clone`, the following things work: https://git-scm.com/docs/git-clone#_git_urls_a_id_urls_a.

Interesting for `jb` are the following:

* `ssh://[user@]host.xz[:port]/path/to/repo.git/`: Regular `ssh` syntax, also the one we use for cloning packages.
* `http[s]://host.xz[:port]/path/to/repo.git/`: Regular `http` syntax, most easy to use as it requires no auth at all
* **`[user@]host.xz:path/to/repo.git/`**: **Special**: SCP syntax, alternative form for `ssh`. Used by GitHub as SSH in the clone instructions. Note that this syntax specifies **no protocol** at all.

However, the `scp` and `ssh` forms are incompatible, because **`ssh` uses the colon for the port**, while `scp` uses it for the **username**.

---

This means to really solve this, we need to add proper support for `scp`:

1. Recognize the difference between `ssh://user@host/path` and `user@host:path`
2. Parse both into a `*Git`, both using `gitSchemeSSH`

I'll implement this and create a PR soon

**Comment by sh0rez** [comment]
Apparently, `jb` never had a proper implementation:

v0.2.0 had this test:
https://github.com/jsonnet-bundler/jsonnet-bundler/blob/184841238bb5df1b886ccaecd3e179bc55c17687/cmd/jb/main_test.go#L65

This format is invalid, because it uses a colon, where git expects a slash.
